coords_terminologies = {
    "area": "ISO3",
    "category": "IPCC2006_PRIMAP",
    "scenario": "PRIMAP",
}

# define config dict
inv_conf = {
    "entity_row": 0,
    "unit_row": 1,
    "index_cols": "Greenhouse gas source and sink categories",
    "header_long": ["orig_cat_name", "entity", "unit", "time", "data"],
    "cat_code_regexp": r"^(?P<code>[a-zA-Z0-9\.]{1,11})[\s\.].*",
    "2005": {
        "pages_to_read": ["197", "198", "199", "200"],
        "header": [
            "Greenhouse gas source and sink categories",
            "CO2",
            "CH4",
            "N2O",
            "HFCs",
            "PFCs",
            "SF6",
            "Other halogenated gases with CO2 equivalent conversion factors",
            "Other halogenated gases without CO2 equivalent conversion factors" "NOx",
            "CO",
            "NMVOCs",
            "SO2",
        ],
        "unit": [
            "-",
            "Gg",
            "Gg",
            "Gg",
            "GgCO2eq",
            "GgCO2eq",
            "GgCO2eq",
            "GgCO2eq",
            "Gg",
            "Gg",
            "Gg",
            "Gg",
            "Gg",
        ],
        "cat_codes_manual": {
            "Memo Items (5)": "MEMO",
            "International Bunkers": "M.BK",
            "1.A.3.a.i - International Aviation (International Bunkers) (1)": "M.BK.A",
            "1.A.3.d.i - International water-borne navigation (International bunkers) (1)": "M.BK.M",
            "1.A.5.c - Multilateral Operations (1)(2)": "M.MULTIOP",
            "Total National Emissions and Removals": "0",
        },
    },
    "2006": {
        "pages_to_read": ["201", "202", "203", "204"],
        "header": [
            "Greenhouse gas source and sink categories",
            "CO2",
            "CH4",
            "N2O",
            "HFCs",
            "PFCs",
            "SF6",
            "Other halogenated gases with CO2 equivalent conversion factors",
            "Other halogenated gases without CO2 equivalent conversion factors" "NOx",
            "CO",
            "NMVOCs",
            "SO2",
        ],
        "unit": [
            "-",
            "Gg",
            "Gg",
            "Gg",
            "GgCO2eq",
            "GgCO2eq",
            "GgCO2eq",
            "GgCO2eq",
            "Gg",
            "Gg",
            "Gg",
            "Gg",
            "Gg",
        ],
        "cat_codes_manual": {
            "Memo Items (5)": "MEMO",
            "International Bunkers": "M.BK",
            "1.A.3.a.i - International Aviation (International Bunkers) (1)": "M.BK.A",
            "1.A.3.d.i - International water-borne navigation (International bunkers) (1)": "M.BK.M",
            "1.A.5.c - Multilateral Operations (1)(2)": "M.MULTIOP",
            "Total National Emissions and Removals": "0",
        },
    },
}
