name: Install

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 3'

jobs:
  test-pypi-install:
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: [ "3.9", "3.10", "3.11" ]
    steps:
    - name: Set up Python "${{ matrix.python-version }}"
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: "${{ matrix.python-version }}"
    - name: Install
      run: |
        pip install --upgrade pip
        pip install unfccc-ghg-data
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Test installation (${{ matrix.os }} Python ${{ matrix.python-version }})
      run: |
        python scripts/test-install.py
